### ISSUE TITLE
Upload website

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/dev-days-2021#1]
@emdupre @thomasBazeille I just created this repo to mimic the organization from last year as we discussed during our last meeting.
I think that the priority at this point is to work on the communication around the event. 
@emdupre, I think you had a website for the event last year. Do you think you could upload it here so that we can work on updating the information before putting it online?

**Comment by emdupre** [comment]
I don't have push access here, so I just opened a PR to add the initial content !
